# This template contains steps to run performance tests for a single configuration.

parameters:
  image: ''
  platform: ''
  config: 'Release'
  arch: 'x64'
  tls: ''
  disableEncryption: false
  extraArgs: '-Publish'

jobs:
- job: performance_${{ parameters.platform }}_${{ parameters.arch }}_${{ parameters.tls }}_${{ parameters.disableEncryption }}
  ${{ if eq(parameters.disableEncryption, true) }}:
    displayName: windows ${{ parameters.arch }} ${{ parameters.tls }}_cleartext
  ${{ if eq(parameters.disableEncryption, false) }}:
    displayName: windows ${{ parameters.arch }} ${{ parameters.tls }}
  pool:
    vmImage: ${{ parameters.image }}
  variables:
  - name: runCodesignValidationInjection
    value: false
  - name: skipComponentGovernanceDetection
    value: true
  steps:
  - checkout: self

  - template: ./download-artifacts.yml
    parameters:
      platform: ${{ parameters.platform }}
      arch: ${{ parameters.arch }}
      tls: ${{ parameters.tls }}

  - task: PowerShell@2
    displayName: Prepare Test Machine
    inputs:
      pwsh: true
      filePath: scripts/prepare-machine.ps1
      arguments: -Configuration Test

  - task: PowerShell@2
    displayName: Run Performance Test
    timeoutInMinutes: 12
    continueOnError: true
    inputs:
      pwsh: true
      filePath: scripts/performance.ps1
      ${{ if eq(parameters.disableEncryption, true) }}:
        arguments: -DisableEncryption -Config ${{ parameters.config }} -Arch ${{ parameters.arch }} -Tls ${{ parameters.tls }} ${{ parameters.extraArgs }}
      ${{ if eq(parameters.disableEncryption, false) }}:
        arguments: -Config ${{ parameters.config }} -Arch ${{ parameters.arch }} -Tls ${{ parameters.tls }} ${{ parameters.extraArgs }}

  - task: CopyFiles@2
    displayName: Move Performance Results
    inputs:
      sourceFolder: artifacts/PerfDataResults
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: Upload Performance Results
    inputs:
      artifactName: performance
      pathToPublish: $(Build.ArtifactStagingDirectory)
      parallel: true
